import stylistic from '@stylistic/eslint-plugin';
import importXPlugin from 'eslint-plugin-import-x';
import globals from 'globals';
import tseslint from 'typescript-eslint';

/*
 * This rule set is a direct, one-time port of the project's effective ESLint 8 configuration (airbnb-base +
 * airbnb-typescript + every project-specific override the former .eslintrc.cjs carried). See DEVELOPMENT.md,
 * ESLint configuration section, for the rationale and how to handle future upgrades.
 *
 * Rules renamed on the way in (same rule, same behaviour, new id only):
 *   - formatting rules typescript-eslint v7 shipped and v8 dropped now live under @stylistic/* (brace-style,
 *     comma-dangle, comma-spacing, func-call-spacing, indent, keyword-spacing, lines-between-class-members,
 *     no-extra-parens, no-extra-semi, object-curly-spacing, quotes, semi, space-before-blocks,
 *     space-before-function-paren, space-infix-ops).
 *   - @typescript-eslint/no-throw-literal is now @typescript-eslint/only-throw-error.
 *   - import/* is now import-x/*.
 */

export default tseslint.config(
    {
        ignores: [
            'platforms/**',
            'temp/**',
            'dist/**',
        ],
    },
    {
        plugins: {
            'import-x': importXPlugin,
            '@stylistic': stylistic,
            '@typescript-eslint': tseslint.plugin,
        },
        settings: {
            'import-x/extensions': ['.js', '.mjs', '.jsx', '.ts', '.tsx', '.d.ts'],
            'import-x/external-module-folders': ['node_modules', 'node_modules/@types'],
            'import-x/parsers': {
                '@typescript-eslint/parser': ['.ts', '.tsx', '.d.ts'],
            },
            'import-x/resolver': {
                typescript: true,
            },
        },
        languageOptions: {
            globals: globals.node,
            parser: tseslint.parser,
            parserOptions: {
                project: './tsconfig.json',
                tsconfigRootDir: import.meta.dirname,
            },
        },
        rules: {
            '@stylistic/brace-style': ['error',
                '1tbs',
                {
                    allowSingleLine: true,
                },
            ],
            '@stylistic/comma-dangle': ['error', 'always-multiline'],
            '@stylistic/comma-spacing': ['error',
                {
                    before: false,
                    after: true,
                },
            ],
            '@stylistic/function-call-spacing': ['error', 'never'],
            '@stylistic/indent': ['error', 4],
            '@stylistic/keyword-spacing': ['error',
                {
                    before: true,
                    after: true,
                    overrides: {
                        return: {
                            after: true,
                        },
                        throw: {
                            after: true,
                        },
                        case: {
                            after: true,
                        },
                    },
                },
            ],
            '@stylistic/lines-between-class-members': ['error',
                'always',
                {
                    exceptAfterSingleLine: false,
                    exceptAfterOverload: true,
                },
            ],
            '@stylistic/no-extra-semi': 'error',
            '@stylistic/object-curly-spacing': ['error', 'always'],
            '@stylistic/quotes': ['error',
                'single',
                {
                    avoidEscape: true,
                },
            ],
            '@stylistic/semi': ['error', 'always'],
            '@stylistic/space-before-blocks': 'error',
            '@stylistic/space-before-function-paren': ['error',
                {
                    anonymous: 'always',
                    named: 'never',
                    asyncArrow: 'always',
                },
            ],
            '@stylistic/space-infix-ops': 'error',
            '@typescript-eslint/default-param-last': 'error',
            '@typescript-eslint/dot-notation': ['error',
                {
                    allowKeywords: true,
                    allowPattern: '',
                    allowPrivateClassPropertyAccess: false,
                    allowProtectedClassPropertyAccess: false,
                    allowIndexSignaturePropertyAccess: false,
                },
            ],
            '@typescript-eslint/naming-convention': ['error',
                {
                    selector: 'variable',
                    format: null,
                    filter: {
                        regex: '^(__filename|__dirname)$',
                        match: true,
                    },
                },
            ],
            '@typescript-eslint/no-array-constructor': 'error',
            '@typescript-eslint/no-dupe-class-members': 'error',
            '@typescript-eslint/no-empty-function': ['error',
                {
                    allow: ['arrowFunctions', 'functions', 'methods'],
                },
            ],
            '@typescript-eslint/no-explicit-any': 'error',
            '@typescript-eslint/no-implied-eval': 'error',
            '@typescript-eslint/no-loop-func': 'error',
            '@typescript-eslint/no-loss-of-precision': 'error',
            '@typescript-eslint/no-redeclare': 'error',
            '@typescript-eslint/no-shadow': 'error',
            '@typescript-eslint/no-unused-expressions': ['error',
                {
                    allowShortCircuit: false,
                    allowTernary: false,
                    allowTaggedTemplates: false,
                    enforceForJSX: false,
                },
            ],
            '@typescript-eslint/no-unused-vars': ['error',
                {
                    vars: 'all',
                    args: 'after-used',
                    ignoreRestSiblings: true,
                },
            ],
            '@typescript-eslint/no-use-before-define': ['error',
                {
                    functions: true,
                    classes: true,
                    variables: true,
                },
            ],
            '@typescript-eslint/no-useless-constructor': 'error',
            '@typescript-eslint/only-throw-error': 'error',
            '@typescript-eslint/return-await': ['error', 'in-try-catch'],
            'array-bracket-spacing': ['error', 'never'],
            'array-callback-return': ['error',
                {
                    allowImplicit: true,
                    checkForEach: false,
                    allowVoid: false,
                },
            ],
            'arrow-parens': ['error', 'always'],
            'arrow-spacing': ['error',
                {
                    before: true,
                    after: true,
                },
            ],
            'block-scoped-var': 'error',
            'block-spacing': ['error', 'always'],
            'class-methods-use-this': ['error',
                {
                    exceptMethods: [],
                    enforceForClassFields: true,
                },
            ],
            'comma-style': ['error',
                'last',
                {
                    exceptions: {
                        ArrayExpression: false,
                        ArrayPattern: false,
                        ArrowFunctionExpression: false,
                        CallExpression: false,
                        FunctionDeclaration: false,
                        FunctionExpression: false,
                        ImportDeclaration: false,
                        ObjectExpression: false,
                        ObjectPattern: false,
                        VariableDeclaration: false,
                        NewExpression: false,
                    },
                },
            ],
            'computed-property-spacing': ['error', 'never'],
            'constructor-super': 'error',
            curly: ['error', 'multi-line'],
            'default-case': ['error',
                {
                    commentPattern: '^no default$',
                },
            ],
            'default-case-last': 'error',
            'dot-location': ['error', 'property'],
            'eol-last': ['error', 'always'],
            eqeqeq: ['error',
                'always',
                {
                    null: 'ignore',
                },
            ],
            'for-direction': 'error',
            'function-call-argument-newline': ['error', 'consistent'],
            'function-paren-newline': ['error', 'multiline-arguments'],
            'generator-star-spacing': ['error',
                {
                    before: false,
                    after: true,
                },
            ],
            'getter-return': ['error',
                {
                    allowImplicit: true,
                },
            ],
            'global-require': 'error',
            'grouped-accessor-pairs': 'error',
            'guard-for-in': 'error',
            'implicit-arrow-linebreak': ['error', 'beside'],
            'import-x/export': 'error',
            'import-x/first': 'error',
            'import-x/named': 'error',
            'import-x/newline-after-import': 'error',
            'import-x/no-absolute-path': 'error',
            'import-x/no-amd': 'error',
            'import-x/no-cycle': ['error',
                {
                    maxDepth: '∞',
                    ignoreExternal: false,
                    allowUnsafeDynamicCyclicDependency: false,
                },
            ],
            'import-x/no-duplicates': 'error',
            'import-x/no-dynamic-require': 'error',
            'import-x/no-import-module-exports': ['error',
                {
                    exceptions: [],
                },
            ],
            'import-x/no-mutable-exports': 'error',
            'import-x/no-named-as-default': 'error',
            'import-x/no-named-as-default-member': 'error',
            'import-x/no-named-default': 'error',
            'import-x/no-relative-packages': 'error',
            'import-x/no-self-import': 'error',
            'import-x/no-unresolved': ['error',
                {
                    commonjs: true,
                    caseSensitive: true,
                    caseSensitiveStrict: false,
                },
            ],
            'import-x/no-useless-path-segments': ['error',
                {
                    commonjs: true,
                },
            ],
            'import-x/no-webpack-loader-syntax': 'error',
            'import-x/order': ['error',
                {
                    groups: [
                        ['builtin', 'external', 'internal'],
                    ],
                    distinctGroup: true,
                    sortTypesGroup: false,
                    named: false,
                    warnOnUnassignedImports: false,
                },
            ],
            'key-spacing': ['error',
                {
                    beforeColon: false,
                    afterColon: true,
                },
            ],
            'linebreak-style': ['error', 'unix'],
            'lines-around-directive': ['error',
                {
                    before: 'always',
                    after: 'always',
                },
            ],
            'max-classes-per-file': ['error', 1],
            'max-len': ['error',
                {
                    code: 120,
                    comments: 120,
                    tabWidth: 4,
                    ignoreUrls: true,
                    ignoreTrailingComments: false,
                    ignoreComments: false,
                },
            ],
            'new-cap': ['error',
                {
                    newIsCap: true,
                    newIsCapExceptions: [],
                    capIsNew: false,
                    capIsNewExceptions: ['Immutable.Map', 'Immutable.Set', 'Immutable.List'],
                    properties: true,
                },
            ],
            'new-parens': 'error',
            'newline-per-chained-call': ['error',
                {
                    ignoreChainWithDepth: 4,
                },
            ],
            'no-alert': 'warn',
            'no-async-promise-executor': 'error',
            'no-await-in-loop': 'error',
            'no-buffer-constructor': 'error',
            'no-caller': 'error',
            'no-case-declarations': 'error',
            'no-class-assign': 'error',
            'no-compare-neg-zero': 'error',
            'no-cond-assign': ['error', 'always'],
            'no-confusing-arrow': ['error',
                {
                    allowParens: true,
                    onlyOneSimpleParam: false,
                },
            ],
            'no-console': 'warn',
            'no-const-assign': 'error',
            'no-constant-condition': 'warn',
            'no-constructor-return': 'error',
            'no-control-regex': 'error',
            'no-debugger': 'error',
            'no-delete-var': 'error',
            'no-dupe-args': 'error',
            'no-dupe-else-if': 'error',
            'no-dupe-keys': 'error',
            'no-duplicate-case': 'error',
            'no-else-return': ['error',
                {
                    allowElseIf: false,
                },
            ],
            'no-empty': 'error',
            'no-empty-character-class': 'error',
            'no-empty-pattern': 'error',
            'no-eval': 'error',
            'no-ex-assign': 'error',
            'no-extend-native': 'error',
            'no-extra-bind': 'error',
            'no-extra-boolean-cast': 'error',
            'no-extra-label': 'error',
            'no-fallthrough': 'error',
            'no-floating-decimal': 'error',
            'no-func-assign': 'error',
            'no-global-assign': ['error',
                {
                    exceptions: [],
                },
            ],
            'no-import-assign': 'error',
            'no-inner-declarations': 'error',
            'no-invalid-regexp': 'error',
            'no-irregular-whitespace': 'error',
            'no-iterator': 'error',
            'no-label-var': 'error',
            'no-labels': ['error',
                {
                    allowLoop: false,
                    allowSwitch: false,
                },
            ],
            'no-lone-blocks': 'error',
            'no-lonely-if': 'error',
            'no-misleading-character-class': 'error',
            'no-mixed-operators': ['error',
                {
                    groups: [
                        ['%', '**'],
                        ['%', '+'],
                        ['%', '-'],
                        ['%', '*'],
                        ['%', '/'],
                        ['/', '*'],
                        ['&', '|', '<<', '>>', '>>>'],
                        ['==', '!=', '===', '!=='],
                        ['&&', '||'],
                    ],
                    allowSamePrecedence: false,
                },
            ],
            'no-mixed-spaces-and-tabs': 'error',
            'no-multi-assign': 'error',
            'no-multi-spaces': ['error',
                {
                    ignoreEOLComments: true,
                },
            ],
            'no-multi-str': 'error',
            'no-multiple-empty-lines': ['error',
                {
                    max: 1,
                    maxBOF: 0,
                    maxEOF: 0,
                },
            ],
            'no-nested-ternary': 'error',
            'no-new': 'error',
            'no-new-object': 'error',
            'no-new-require': 'error',
            'no-new-symbol': 'error',
            'no-new-wrappers': 'error',
            'no-nonoctal-decimal-escape': 'error',
            'no-obj-calls': 'error',
            'no-octal': 'error',
            'no-octal-escape': 'error',
            'no-path-concat': 'error',
            'no-plusplus': 'error',
            'no-promise-executor-return': 'error',
            'no-proto': 'error',
            'no-regex-spaces': 'error',
            'no-restricted-exports': ['error',
                {
                    restrictedNamedExports: ['default', 'then'],
                },
            ],
            'no-restricted-globals': ['error',
                {
                    name: 'isFinite',
                    message: 'Use Number.isFinite instead https://github.com/airbnb/javascript#standard-library--isfinite',
                },
                {
                    name: 'isNaN',
                    message: 'Use Number.isNaN instead https://github.com/airbnb/javascript#standard-library--isnan',
                },
                'addEventListener',
                'blur',
                'close',
                'closed',
                'confirm',
                'defaultStatus',
                'defaultstatus',
                'event',
                'external',
                'find',
                'focus',
                'frameElement',
                'frames',
                'history',
                'innerHeight',
                'innerWidth',
                'length',
                'location',
                'locationbar',
                'menubar',
                'moveBy',
                'moveTo',
                'name',
                'onblur',
                'onerror',
                'onfocus',
                'onload',
                'onresize',
                'onunload',
                'open',
                'opener',
                'opera',
                'outerHeight',
                'outerWidth',
                'pageXOffset',
                'pageYOffset',
                'parent',
                'print',
                'removeEventListener',
                'resizeBy',
                'resizeTo',
                'screen',
                'screenLeft',
                'screenTop',
                'screenX',
                'screenY',
                'scroll',
                'scrollbars',
                'scrollBy',
                'scrollTo',
                'scrollX',
                'scrollY',
                'self',
                'status',
                'statusbar',
                'stop',
                'toolbar',
                'top',
            ],
            'no-restricted-properties': ['error',
                {
                    object: 'arguments',
                    property: 'callee',
                    message: 'arguments.callee is deprecated',
                },
                {
                    object: 'global',
                    property: 'isFinite',
                    message: 'Please use Number.isFinite instead',
                },
                {
                    object: 'self',
                    property: 'isFinite',
                    message: 'Please use Number.isFinite instead',
                },
                {
                    object: 'window',
                    property: 'isFinite',
                    message: 'Please use Number.isFinite instead',
                },
                {
                    object: 'global',
                    property: 'isNaN',
                    message: 'Please use Number.isNaN instead',
                },
                {
                    object: 'self',
                    property: 'isNaN',
                    message: 'Please use Number.isNaN instead',
                },
                {
                    object: 'window',
                    property: 'isNaN',
                    message: 'Please use Number.isNaN instead',
                },
                {
                    property: '__defineGetter__',
                    message: 'Please use Object.defineProperty instead.',
                },
                {
                    property: '__defineSetter__',
                    message: 'Please use Object.defineProperty instead.',
                },
                {
                    object: 'Math',
                    property: 'pow',
                    message: 'Use the exponentiation operator (**) instead.',
                },
            ],
            'no-restricted-syntax': ['error',
                {
                    selector: 'ForInStatement',
                    message: 'for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array.',
                },
                {
                    selector: 'ForOfStatement',
                    message: 'iterators/generators require regenerator-runtime, which is too heavyweight for this guide to allow them. Separately, loops should be avoided in favor of array iterations.',
                },
                {
                    selector: 'LabeledStatement',
                    message: 'Labels are a form of GOTO; using them makes code confusing and hard to maintain and understand.',
                },
                {
                    selector: 'WithStatement',
                    message: '`with` is disallowed in strict mode because it makes code impossible to predict and optimize.',
                },
            ],
            'no-return-assign': ['error', 'always'],
            'no-script-url': 'error',
            'no-self-assign': ['error',
                {
                    props: true,
                },
            ],
            'no-self-compare': 'error',
            'no-sequences': 'error',
            'no-setter-return': 'error',
            'no-shadow-restricted-names': 'error',
            'no-spaced-func': 'error',
            'no-sparse-arrays': 'error',
            'no-tabs': 'error',
            'no-template-curly-in-string': 'error',
            'no-this-before-super': 'error',
            'no-trailing-spaces': ['error',
                {
                    skipBlankLines: false,
                    ignoreComments: false,
                },
            ],
            'no-undef': 'error',
            'no-undef-init': 'error',
            'no-unexpected-multiline': 'error',
            'no-unneeded-ternary': ['error',
                {
                    defaultAssignment: false,
                },
            ],
            'no-unreachable': 'error',
            'no-unreachable-loop': ['error',
                {
                    ignore: [],
                },
            ],
            'no-unsafe-finally': 'error',
            'no-unsafe-negation': 'error',
            'no-unsafe-optional-chaining': ['error',
                {
                    disallowArithmeticOperators: true,
                },
            ],
            'no-unused-labels': 'error',
            'no-useless-backreference': 'error',
            'no-useless-catch': 'error',
            'no-useless-computed-key': 'error',
            'no-useless-concat': 'error',
            'no-useless-rename': ['error',
                {
                    ignoreDestructuring: false,
                    ignoreImport: false,
                    ignoreExport: false,
                },
            ],
            'no-useless-return': 'error',
            'no-var': 'error',
            'no-void': 'error',
            'no-whitespace-before-property': 'error',
            'no-with': 'error',
            'nonblock-statement-body-position': ['error',
                'beside',
                {
                    overrides: {},
                },
            ],
            'object-curly-newline': ['error',
                {
                    ObjectExpression: {
                        minProperties: 4,
                        multiline: true,
                        consistent: true,
                    },
                    ObjectPattern: {
                        minProperties: 4,
                        multiline: true,
                        consistent: true,
                    },
                    ImportDeclaration: {
                        minProperties: 4,
                        multiline: true,
                        consistent: true,
                    },
                    ExportDeclaration: {
                        minProperties: 4,
                        multiline: true,
                        consistent: true,
                    },
                },
            ],
            'object-property-newline': ['error',
                {
                    allowAllPropertiesOnSameLine: true,
                    allowMultiplePropertiesPerLine: false,
                },
            ],
            'object-shorthand': ['error',
                'always',
                {
                    ignoreConstructors: false,
                    avoidQuotes: true,
                },
            ],
            'one-var': ['error', 'never'],
            'one-var-declaration-per-line': ['error', 'always'],
            'operator-assignment': ['error', 'always'],
            'operator-linebreak': ['error',
                'before',
                {
                    overrides: {
                        '=': 'none',
                    },
                },
            ],
            'padded-blocks': ['error',
                {
                    blocks: 'never',
                    classes: 'never',
                    switches: 'never',
                },
                {
                    allowSingleLineBlocks: true,
                },
            ],
            'prefer-arrow-callback': ['error',
                {
                    allowNamedFunctions: false,
                    allowUnboundThis: true,
                },
            ],
            'prefer-const': ['error',
                {
                    destructuring: 'any',
                    ignoreReadBeforeAssign: true,
                },
            ],
            'prefer-destructuring': ['error',
                {
                    VariableDeclarator: {
                        array: false,
                        object: true,
                    },
                    AssignmentExpression: {
                        array: true,
                        object: false,
                    },
                },
                {
                    enforceForRenamedProperties: false,
                },
            ],
            'prefer-exponentiation-operator': 'error',
            'prefer-numeric-literals': 'error',
            'prefer-object-spread': 'error',
            'prefer-promise-reject-errors': ['error',
                {
                    allowEmptyReject: true,
                },
            ],
            'prefer-regex-literals': ['error',
                {
                    disallowRedundantWrapping: true,
                },
            ],
            'prefer-rest-params': 'error',
            'prefer-spread': 'error',
            'prefer-template': 'error',
            radix: 'error',
            'require-yield': 'error',
            'rest-spread-spacing': ['error', 'never'],
            'semi-spacing': ['error',
                {
                    before: false,
                    after: true,
                },
            ],
            'semi-style': ['error', 'last'],
            'space-in-parens': ['error', 'never'],
            'space-unary-ops': ['error',
                {
                    words: true,
                    nonwords: false,
                    overrides: {},
                },
            ],
            'spaced-comment': ['error',
                'always',
                {
                    line: {
                        exceptions: ['-', '+'],
                        markers: ['=', '!', '/'],
                    },
                    block: {
                        exceptions: ['-', '+'],
                        markers: ['=', '!', ':', '::'],
                        balanced: true,
                    },
                },
            ],
            'switch-colon-spacing': ['error',
                {
                    after: true,
                    before: false,
                },
            ],
            'symbol-description': 'error',
            'template-curly-spacing': 'error',
            'template-tag-spacing': ['error', 'never'],
            'unicode-bom': ['error', 'never'],
            'use-isnan': 'error',
            'valid-typeof': ['error',
                {
                    requireStringLiterals: true,
                },
            ],
            'vars-on-top': 'error',
            'yield-star-spacing': ['error', 'after'],
            yoda: 'error',
        },
    },
    {
        // Ported from airbnb-typescript's overrides block (files: ['*.ts', '*.tsx']): rules that become
        // redundant once TypeScript's own checks apply, plus the project's own explicit-function-return-type
        // override for .ts files.
        files: ['**/*.ts'],
        rules: {
            '@typescript-eslint/explicit-function-return-type': 'error',
            'constructor-super': 'off',
            'getter-return': 'off',
            'import-x/named': 'off',
            'import-x/no-named-as-default-member': 'off',
            'import-x/no-unresolved': 'off',
            'no-const-assign': 'off',
            'no-dupe-args': 'off',
            'no-dupe-keys': 'off',
            'no-func-assign': 'off',
            'no-import-assign': 'off',
            'no-new-symbol': 'off',
            'no-obj-calls': 'off',
            'no-setter-return': 'off',
            'no-this-before-super': 'off',
            'no-undef': 'off',
            'no-unreachable': 'off',
            'no-unsafe-negation': 'off',
            'valid-typeof': 'off',
        },
    },
    {
        // eslint.config.js is not part of tsconfig.json's include list, so it cannot be linted with
        // type-aware parserOptions.project. A few ported rules (dot-notation, naming-convention) require type
        // information unconditionally in typescript-eslint v8; disableTypeChecked turns those off for this file.
        files: ['eslint.config.js'],
        extends: [tseslint.configs.disableTypeChecked],
        languageOptions: {
            parserOptions: {
                project: null,
            },
        },
        rules: {
            // tseslint's documented default-export API (tseslint.plugin, .parser, .configs) trips this rule.
            'import-x/no-named-as-default-member': 'off',
            // The ported rule messages below are quoted verbatim from their source and cannot be rewrapped.
            'max-len': 'off',
        },
    },
);
